spring:
  cloud:
    gateway:
      default-filters:
      - TokenRelay
      - RemoveRequestHeader=Cookie
      routes:
      - id: api-route
        uri: '${API_ROUTES_URI: http://localhost:8080/}'
        predicates:
        - Path=/stuff
      - id: frontend-route
        uri: '${UI_ROUTES_URI: http://localhost:3000/}'
        predicates:
        - Path=/**
  security:
    oauth2:
      client:
        provider:
          okta:
            issuer-uri: https://dev-42225833.okta.com
        registration:
          okta:
          # export CLIENT_ID=xxx
            client-id: '${vcap.services.test-credhub.credentials.CLIENT_ID:0oa7d5z3gs4jmavo25d7}'
            client-secret: '${vcap.services.test-credhub.credentials.CLIENT_SECRET:CKxV1FKO6vtT5FwVpOm3KxnzNUBwcQXU41SbEPEC}'
            scope: openid,profile,email
logging:
  level:
    org.springframework.cloud.gateway: TRACE
    org.springframework.http.server.reactive: DEBUG
    org.springframework.web.reactive: DEBUG
    org.springframework.security: DEBUG
    reactor.ipc.netty: DEBUG
    reactor.netty: DEBUG