spring:
  cloud:
    gateway:
      routes:
      - id: api-route
        uri: http://stuff-api.apps.internal:8080
        predicates:
        - Path=/stuff
      - id: frontend-route
        uri: http://stuff-ui.apps.internal:8080
        predicates:
        - Path=/**

logging:
  level:
    org.springframework.cloud.gateway: TRACE
    org.springframework.http.server.reactive: DEBUG
    org.springframework.web.reactive: DEBUG
    reactor.ipc.netty: DEBUG
    reactor.netty: DEBUG