spring:
  cloud:
    gateway:
      routes:
      - id: api-route
        uri: http://localhost:8080
        predicates:
        - Path=/stuff
        # filters:
        # - TokenRelay=
        # - RemoveRequestHeader=Cookie
      - id: frontend-route
        uri: http://localhost:3000
        predicates:
        - Path=/**
        # filters:
        # - TokenRelay=
        # - RemoveRequestHeader=Cookie
  security:
    oauth2:
      client:
        provider:
          okta:
            issuer-uri: https://dev-42225833.okta.com/oauth2/default
        registration:
          okta:
            # client-id: 0oa7d5z3gs4jmavo25d7
            client-id: ${vcap.services.my-creds.credentials.OKTA_CLIENT_ID}
            # client-secret: CKxV1FKO6vtT5FwVpOm3KxnzNUBwcQXU41SbEPEC
            client-secret: ${vcap.services.my-creds.credentials.OKTA_CLIENT_SECRET}
            authorization-grant-type: authorization_code
            scope: openid,profile,email
logging:
  level:
    org.springframework:
      cloud.gateway: TRACE
      # http.server.reactive: DEBUG
      # web.reactive: DEBUG
      security: DEBUG   
    # reactor.ipc.netty: DEBUG
    # reactor.netty: DEBUG